name: First Interaction

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Message with markdown. This is the message that will be displayed on users first issue'
          pr-message: 'Message that will be displayed on users first pr. Look, a `code block` for markdown'

